### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by varjolintu** [varjolintu/keepassxc#1]
This post will be updated as the project progresses. 

**Tasks**
- [x] Asynchronous cross-platform way to read stdin (Native Messaging host)
- [x] libsodium integration
- [x] Sending correct error replies
- [x] Compile with Linux
- [x] Compile with Windows (not even tested yet)
- [x] Test an AppImage for Linux
- [x] Test a snap image for Linux
- [x] Add a [proxy](https://github.com/varjolintu/keepassxc-proxy) application support 
- [x] Changed localhost UDP port listening for proxy application as optional, disabled by default.
- [x] Added support for extended ASCII characters and passphrases in password generator
- [x] Fixed pfn/passifox#583
- [x] Allow multiple UDP clients simultaneously
- [ ] Support for OTP codes
- [x] Support for UNIX sockets

**Bugs**
- [x] Crash when showing keepassxc-browser `associate` dialog for setting the client name
- [x] Crash when showing allow/deny dialog when using an entry for the first time
- [x] Database hash and `associate` are available even when database is closed
- [x] Fix for keepassxreboot/keepassxc#28
- [x] Fix the damn icon bug

**Other**
- [ ] A way to confirm requests are really coming from keepassxc-browser? Needed?

**Current TODO list**
- [x] Update Native Messaging JSON scripts with KeePassXC location which each start
- [x] Update HostInstaller class
- [x] Replace UDP for proxy application with Unix Domain sockets with Linux/Unix/macOS
- [x] Replace boost with plain Qt classes
- [ ] Add keepassxc-proxy to the main keepassxc project as optional feature and separate binary
